apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital
  labels:
    app: hospital

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hospital
  
  template:
    metadata:
      labels:
        app: hospital

    spec:
      containers:
        - name: hospital
          image: verbose2001/test:3
          ports:
            - containerPort: 8084

---

apiVersion: v1
kind: Service
metadata:
  name: hospital
spec:
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  
  selector:
    app: hospital
  type: LoadBalancer
