name: CI_hospital_management 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: setup_docker
        run: |
          docker build -t hospital_management .

      - name: docker_run
        run: docker run -dt -p 8084:8084 hospital_management
          
      - name: docker_upload
        run: |
          docker tag verbose2001/hospital_management:latest
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push verbose2001/hospital_management:latest
