name: CICD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout_code
        uses: actions/checkout@v4

      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with maven
        run: |
          mvn -B clean test --file pom.xml
          mvn -B package --file pom.xml
          mkdir application && cp target/*.war application
      
      - name: upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          filename: application/*.war
          path: application

  Download_job:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          filename: application/*.war
          path : application
