name: CI_pipeline

on:
  push:
    branches: [ main ]

jobs:
  Build_and_upload:
    runs-on: ubuntu-latest
    strategy:
      metrix:
        java-version-strategy: [17]
      
    steps:
    - name : set-up_python_env
      uses: actions/setup-java@v5
      with:
        java-version: ${{metrix.java-version-strategy}}
    
    - name : Git_checkout
      uses: actions/checkout@v4
      
    - name: build
      run: |
        mvn -B package --file pom.xml
	mkdir staging && cp /target/*.jar stagin

    - name: upload
      uses: actions/upload-artifacts@v4
      with:
        name: my-artifact
        path: target/*.jar
	
  Build_download:
    runs-on: [ubuntu-linunx]
    needs: Build_and_upload
	
      steps:
      - name: download_the_artifact
	uses: actions/download-artifacts@v4
	with:
	  name: my-artifact
	  path: ./artifacts
	run: echo 'Artifacts downloaded!!'
