name: CICD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Maven_build
        run: |
          mvn -B test --file pom.xml
          mvn -B package --file pom.xml
          mkdir build-artifacts && cp -r target/*.jar build-artifacts/

        
      - name: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          file: build-artifacts/*.jar
          path: build-artifacts

  download:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download-artifacts
        uses: actions/download-artifact@v4
        with:
          file: build-artifacts/*.jar
          path: build-artifacts
